script:
  build: bootstrap/
  links:
    - db
  environment:
    - PGHOST=db
  volumes:
    - tmp/osmosis/:/tmp/osmosis/
excerpt:
  build: osmaxx_excerpt/
  links:
    - db
  environment:
    - PGHOST=db
  volumes:
    - results:/home/excerpt/data/
db:
  image: geometalab/postgis-with-translit
