data:
  image: debian:jessie
  command: echo true
  volumes:
    - /tmp/osm

rqdashboard:
  build: rq-dashboard
  links:
    - redis
  ports:
    - "9090:9181"
  command: rq-dashboard -H redis

redis:
  image: redis

api:
  extends:
    file: common-services.yml
    service: environmentvars
  build: .
  dockerfile: ./Dockerfile.rest_api
  command: [honcho, -f, ./conversion_service/Procfile, start]
  volumes_from:
    - data
  links:
    - redis
  environment:
    - DJANGO_SETTINGS_MODULE=conversion_service.config.settings.local

worker:
  extends:
    file: common-services.yml
    service: environmentvars
  build: .
  dockerfile: ./Dockerfile.worker
  command: [honcho, -f, ./conversion_service/worker/Procfile, start]
  volumes_from:
    - data
  links:
    - redis
  environment:
    - DJANGO_SETTINGS_MODULE=conversion_service.config.settings.worker
