data:
  image: busybox
  command: echo true
  volumes:
    - /home/njordan/tmp/t:/tmp

rqdashboard:
  build: rq-dashboard
  links:
    - redis
  ports:
    - "9090:9181"
  command: rq-dashboard -H redis

redis:
  image: redis

# 3 workers
worker1:
  extends:
    file: common-services.yml
    service: webapp
  build: .
  volumes_from:
    - data
  links:
    - workerdatabase1:database
    - redis
  environment:
    - PGHOST=database

workerdatabase1:
  image: geometalab/postgis-with-translit

worker2:
  extends:
    file: common-services.yml
    service: webapp
  build: .
  volumes_from:
    - data
  links:
    - workerdatabase2:database
    - redis
  environment:
    - PGHOST=database

workerdatabase2:
  image: geometalab/postgis-with-translit

worker3:
  extends:
    file: common-services.yml
    service: webapp
  build: .
  volumes_from:
    - data
  links:
    - workerdatabase3:database
    - redis
  environment:
    - PGHOST=database

workerdatabase3:
  image: geometalab/postgis-with-translit


