data:
  image: busybox
  command: echo true
  volumes:
    - /home/njordan/tmp/t:/tmp

restapi:
  extends:
    file: common-services.yml
    service: webapp
  build: .
  ports:
    - "8000:8000"
  entrypoint: [honcho, -f, ./rest_api/Procfile, start]
#  entrypoint: [sh, -c]
  volumes:
    - .:/home/py
  volumes_from:
    - data
  links:
    - managerdatabase:database
    - redis
  environment:
    - DJANGO_SETTINGS_MODULE=rest_api.config.settings.local

managerdatabase:
  image: geometalab/postgis:9.4


rqdashboard:
  build: rq-dashboard
  links:
    - redis
  ports:
    - "9090:9181"
  command: rq-dashboard -H redis

redis:
  image: redis

# 1 worker
worker:
  extends:
    file: common-services.yml
    service: webapp
  build: .
  entrypoint: [honcho, -f, ./worker/Procfile, start]
  volumes_from:
    - data
  links:
    - workerdatabase:database
    - redis
  environment:
    - DJANGO_SETTINGS_MODULE=rest_api.config.settings.worker
    - PGHOST=database

workerdatabase:
  image: geometalab/postgis-with-translit
