script:
  build: .
  links:
    - db
  environment:
    - PGHOST=db
  volumes:
    - .:/home/data-wrangler/data-wrangler/
    - tmp/osmosis/:/tmp/osmosis/
db:
  image: geometalab/postgis-with-translit
