data:
  image: busybox
  command: echo true
  volumes:
    - /home/njordan/tmp/t:/tmp

rqdashboard:
  build: rq-dashboard
  links:
    - redis
  ports:
    - "9090:9181"
  command: rq-dashboard -H redis

redis:
  image: redis

# 1 worker
worker:
  extends:
    file: common-services.yml
    service: environmentvars
  build: .
  dockerfile: ./Dockerfile.worker
  entrypoint: [honcho, -f, ./worker/Procfile, start]
  volumes_from:
    - data
  links:
    - redis
  environment:
    - DJANGO_SETTINGS_MODULE=osmaxx_conversion_service.config.settings.worker
    - PGHOST=localhost
