data:
  image: busybox
  command: echo true
  volumes:
    - /tmp
worker:
  build: .
  volumes_from:
    - data
  links:
    - database
  environment:
    - PGHOST=database
database:
  image: geometalab/postgis-with-translit
